document.addEventListener("DOMContentLoaded",async()=>{const list=document.querySelector(".conversations"),body=document.querySelector(".chat-body"),input=document.querySelector(".composer input"),ask=document.querySelector(".ask-nova"),send=document.querySelector(".send"),search=document.querySelector(".search-box input");let conversations=[],selected=null;
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\\\"":"&quot;","'":"&#39;"}[c]));
const initials=v=>(String(v||"?").trim()[0]||"?").toUpperCase();
const empty=text=>{list.innerHTML='<p class="muted" style="padding:20px">'+esc(text)+"</p>";};
function renderList(){if(!conversations.length)return empty("No conversations found.");list.innerHTML=conversations.map(c=>'<button class="conversation '+(selected?.id===c.id?"active":"")+'" data-id="'+c.id+'"><span class="contact-avatar">'+initials(c.display_name||c.wa_id)+'</span><span class="conversation-copy"><strong>'+esc(c.display_name||c.wa_id)+'</strong><small>'+esc(c.tags?.filter(Boolean).join(" · ")||c.status)+'</small></span><span class="conversation-meta"><time>'+Number(c.unread_count||0)+'</time>'+(c.unread_count?'<i class="unread"></i>':"")+"</span></button>").join("");list.querySelectorAll(".conversation").forEach(b=>b.addEventListener("click",()=>selectConversation(b.dataset.id)));}
async function loadMessages(c){const r=await NovaAPI.messages(c.id,{limit:100});const rows=(r.data||[]).slice().reverse();body.innerHTML='<div class="date-divider">Conversation</div>'+ (rows.length?rows.map(m=>'<div class="bubble '+(m.direction==="inbound"?"customer":"ai")+'">'+esc(m.text||"["+m.message_type+"]")+'<time>'+new Date(m.created_at).toLocaleString()+(m.direction==="outbound"?" · Nova/Agent":"")+'</time></div>').join(""):'<p class="muted">No messages yet.</p>');await NovaAPI.readConversation(c.id).catch(()=>{});}
async function selectConversation(id){selected=conversations.find(c=>c.id===id)||null;renderList();if(!selected)return;const head=document.querySelector(".contact-head");if(head)head.querySelector("strong").textContent=selected.display_name||selected.wa_id;await loadMessages(selected);NovaAPI.copilotDrafts(selected.id).then(r=>{const d=r.data?.[0];if(d){const draft=document.createElement("div");draft.className="bubble ai draft";draft.textContent="Latest draft: "+(d.draft||"");body.appendChild(draft);}}).catch(()=>{});}
async function load(){try{const r=await NovaAPI.conversations({limit:100,search:search?.value||""});conversations=r.data||[];if(!conversations.some(c=>c.id===selected?.id))selected=conversations[0]||null;renderList();if(selected)await selectConversation(selected.id);else body.innerHTML='<p class="muted">Select a conversation to view messages.</p>';}catch(e){empty(e.message||"Unable to load conversations.");}}
search?.addEventListener("input",()=>{clearTimeout(search._t);search._t=setTimeout(load,250);});
ask?.addEventListener("click",async()=>{if(!selected)return;const prompt=input?.value.trim()||"Create a concise helpful reply based on the latest customer message.";ask.disabled=true;ask.textContent="Generating…";try{const r=await NovaAPI.copilotDraft(selected.id,prompt);const d=r.data?.draft||"Draft created.";const draft=document.createElement("div");draft.className="bubble ai draft";draft.textContent="Nova draft: "+d;body.appendChild(draft);if(input)input.value=d;}catch(e){alert(e.message);}finally{ask.disabled=false;ask.textContent="✦ Ask Nova";}});
send?.addEventListener("click",()=>alert("Sending is intentionally not wired to the browser composer yet. Use Nova's approved delivery pipeline so tenant limits, idempotency and WhatsApp delivery safety remain enforced."));
await load();});